#!/usr/bin/env zsh

FONT_FACE="Maple Mono"
ICON_FONT_FACE="SF Pro"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

# Colors
COLOR_BG=0xff35183d
COLOR_BORDER=0xff9e5eab

bar=(
    height=32
    color=0x00000000
    margin=0
    sticky=on
    padding_left=23
    padding_right=23
    notch_width=188
    display=main
)

default=(
    background.corner_radius=5
    background.padding_right=5
    background.height=26
    icon.font="$ICON_FONT_FACE:Medium:16.0"
    icon.padding_left=5
    icon.padding_right=5
    label.font="$FONT_FACE:Medium:13.0"
    label.color=0xffcad3f5
    label.y_offset=0
    label.padding_left=0
    label.padding_right=5
)

bracket=(
    background.height=26
    background.color=$COLOR_BG
    background.corner_radius=5
    background.border_color=$COLOR_BORDER
    background.border_width=1.5
)


sketchybar --bar "${bar[@]}" \
    --default "${default[@]}" \
    \
    --add item front_app left \
    --set front_app \
        label.drawing=yes \
        script="$PLUGIN_DIR/front_app.sh" \
    --subscribe front_app front_app_switched \
    \
    \
    \
    --add item clock right \
    --set clock \
        icon=󰃰 \
        icon.color=0xffed8796 \
        update_freq=10 \
        script="$PLUGIN_DIR/clock.sh" \
    \
    --add item battery right \
    --set battery \
        update_freq=20 \
        script="$PLUGIN_DIR/battery.sh" \
    --subscribe battery power_source_change \
    \
    --add item volume right \
    --set volume \
        icon.color=0xff8aadf4 \
        label.drawing=true \
        script="$PLUGIN_DIR/volume.sh" \
        icon.padding_left=8 \
    --subscribe volume volume_change \
    \
    --add bracket right_bracket clock battery volume \
    --set right_bracket "${bracket[@]}" \
    \
    --add item media right \
    --set media \
        icon.drawing=false \
        script="$PLUGIN_DIR/media.sh" \
        scroll_texts=true \
        label.max_chars=60 \
        label.scroll_duration=256 \
    --subscribe media media_change \


# osascript -e 'quit app "Rectangle"'
# open -a Rectangle

##### Finalizing Setup #####
sketchybar --update
#sketchybar --trigger space_change
